language: python
python:
- '3.7'

install:
  - pip install -r requirements.txt
before_deploy:
  - openssl aes-256-cbc -K $encrypted_6c104bd27e75_key -iv $encrypted_6c104bd27e75_iv -in gae-travis-tutorial.json.enc -out gae-travis-tutorial.json -d

jobs:
  include:
    - stage: test
    - script: python test_main.py

deploy:
  provider: gae
  project: "gae-travis-tutorial"
  keyfile: "gae-travis-tutorial.json"
