language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: test
    name: testing
    script: python test_main.py
deploy:
  provider: gae
  project: gae-travis-tutorial
  keyfile: gae-travis-tutorial.json
before_install:
- echo $random_secret
- echo $visible_variable
- openssl aes-256-cbc -K $encrypted_7df9fc7a0daf_key -iv $encrypted_7df9fc7a0daf_iv
  -in api_key.py.sample.enc -out api_key.py.sample -d
